// lets-vote-vue/src/App.vue
<template>
  <VotingContainer />
</template>

<script>
import VotingContainer from './components/VotingContainer.vue';

export default {
  name: 'App',
  components: {
    VotingContainer 
  },
  data() {
    return {
      title: 'Reunião amanhã',
      status: 'open',
      votes: [
        { option: 'Sim', count: 6 }, 
        { option: 'Não', count: 3 },
        { option: 'Talvez', count: 1 },
      ],
    }
  },
  methods: {
    onVote(index) {
      this.votes[index].count++;
      this.changeStatus();
    },
    changeStatus() {
      this.status = this.status == 'open' ? 'closed' : 'open';
    }
  }
}
</script>

<style>

</style>

// lets-vote-react/src/App.js
import VotingCard from './components/VotingCard';

import './styles/global.css';

function App() {
  var votes = [
    { option: 'Sim', count: 6 },
    { option: 'Não', count: 3 },
    { option: 'Talvez', count: 1 },
  ];

  return (
    <div className="App">
      <VotingCard title="Reunião amanhã" status="open" votes={votes} />
    </div>
  );
}

export default App;
