// lets-vote-react/src/App.js
import VotingCard from './components/VotingCard';

import './styles/global.css';

function App() {
  var votes = [
    { option: 'Sim', count: 6 },
    { option: 'Não', count: 3 },
    { option: 'Talvez', count: 1 },
  ];

  return (
    <div className="App">
      <VotingCard title="Reunião amanhã" status="open" votes={votes} />
    </div>
  );
}

export default App;

// lets-vote-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Reunião amanhã';
  status = 'open';
  votes = [
    { option: 'Sim', count: 6 },
    { option: 'Não', count: 3 },
    { option: 'Talvez', count: 1 },
  ];
}

<voting-card [title]="title" [status]="status" [votes]="votes"></voting-card>
