// lets-vote-vue/src/components/Booth.vue
<template>
  <div class="booth-container">
    <button 
      v-for="(option, index) in options" 
      :key="index"
      @click="$emit('vote', index)"
    >
      {{ option }}
    </button>
  </div>
</template>

<script>
export default {
  name: 'Booth',
  props: {
    options: {
      type: Array,
      required: true
    },
  }
}
</script>

<style scoped>
.booth-container {
  display: flex;
  justify-content: space-around;
}
</style>

// lets-vote-angular/src/app/booth.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";

@Component({
  selector: 'booth',
  templateUrl: './booth.component.html',
  styleUrls: ['./booth.component.css']
})

export class BoothComponent {
  @Input() options: any[] = [];
  @Output() vote = new EventEmitter();
}
<div class="booth-container">
  <button *ngFor="let option of options; index as i" (click)="vote.emit(i)">{{ option }}</button>
</div>
