// lets-vote-angular/src/app/result.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: 'result',
  templateUrl: './result.component.html',
  styleUrls: ['./result.component.css']
})

export class ResultComponent {
  @Input() votes: any[] = [];

  get total() {
    if (this.votes.length == 0) {
      return 1;
    }

    return this.votes.reduce((x, y) => x + y.count, 0);
  }

  calculatePercentage(value: number) {
    return Math.round(100 * value / this.total);
  }
}
<div>
  <p *ngFor="let vote of votes; index as i">
    {{i + 1}}. {{vote.option}} - {{vote.count}} votos ({{calculatePercentage(vote.count)}}%)
  </p>
</div>

// lets-vote-svelte/src/components/Result.svelte
<div>
  {#each votes as vote, index (index)}
    <p>
      {index + 1}. {vote.option} - {vote.count} votos ({calculatePercentage(vote.count)}%)
    </p>
  {/each}
</div>

<script>
  export let votes;

  $: total = votes.reduce((x, y) => x + y.count, 0);

  if (votes.length == 0) {
    total = 1;
  }

  function calculatePercentage(value) {
    return Math.round(100 * value / total);
  }
</script>
