// lets-vote-react/src/components/VotingContainer.js

import { useState } from 'react';

import '../styles/global.css';

import VotingCard from './VotingCard';
import VotingForm from './VotingForm';

export default function VotingContainer() {
  const [title, setTitle] = useState("");
  const [isStarted, setIsStarted] = useState(false);
  const [options, setOptions] = useState([]);

  let status = "open";

  function startVotation(data) {
    setTitle(data.title);
    if (Number(data.threeOptions)) {
      setOptions(['Sim', 'Não', 'Talvez']);
    } else {
      setOptions(['Sim', 'Não']);
    }

    setIsStarted(true);
  }

  return (
    <div className="overlay">
      {!isStarted
        ? <VotingForm onStart={startVotation}></VotingForm>
        : <VotingCard title={title} status={status} options={options} />
      }
    </div>
  )
}

// lets-vote-svelte/src/components/VotingContainer.svelte
<div class="overlay">
  {#if isStarted}
    <VotingCard {votes} {title} {status} />
  {:else}
    <VotingForm on:start={startVotation} />
  {/if}
</div>

<script>
  import VotingCard from './VotingCard.svelte';
  import VotingForm from './VotingForm.svelte';

  let isStarted = false;
  let votes = [
    { option: 'Sim', count: 6 },
    { option: 'Não', count: 3 },
    { option: 'Talvez', count: 1 },
  ];

  let title = 'Reunião amanhã';
  let status = 'open';
  let options = [];

  function startVotation(event) {
    let data = event.detail;
    
    title = data.title;
    if (Number(data.threeOptions)) {
      options = ['Sim', 'Não', 'Talvez'];
    } else {
      options = ['Sim', 'Não'];
    }

    isStarted = true;
  }
</script>

<style>
div {
  color: #666666;
  font: 400 1rem "Inter", sans-serif;
}

.overlay {
  background: rgba(242, 243, 245, 0.8);
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;

  display: flex;
  justify-content: center;
  align-items: center;
}

</style>
