// lets-vote-vue/src/components/VotingCard.vue
<template>
  <div class="overlay">
    <div class="card-container">
      <h2 class="title">{{ title }}?</h2>
      <Booth 
        v-if="status == 'open'" 
        :options="options" 
        @vote="$emit('vote', $event)"
      />
      <Result v-else :votes="votes" />
    </div>
  </div>
  
</template>

<script>
import Result from './Result.vue'
import Booth from './Booth.vue';

export default {
  name: 'VotingCard',
  props: {
    title: String,
    status: String,
    votes: Array,
  },
  components: {
    Booth, Result
  },
  computed: {
    options() {
      return this.votes.map(vote => vote.option);
    }
  },
}
</script>

<style scoped>  
.overlay {
  background: rgba(242, 243, 245, 0.8);
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;

  display: flex;
  justify-content: center;
  align-items: center;
}

.card-container {
  background: var(--white);
  width: 100%;
  max-width: 400px;
  padding: 2rem 3rem;
  border-radius: 5px;
  box-shadow: 0 0 60px rgba(0, 0, 0, 0.05);
  text-align: center;
  position: relative;
}

.title {
  color: #2e384d
}
</style>

// lets-vote-svelte/src/components/VotingCard.svelte
<div>
  <div class="overlay">
    <div class="card-container">
      <h2 class="title">{title}?</h2>
      {#if status === 'open'}
          <Booth {options} on:vote={onVote} />
      {:else}
          <Result {votes} />
      {/if}
    </div>
  </div>
</div>

<script>
  import Booth from './Booth.svelte';
  import Result from './Result.svelte';

  export let status;
  export let title;
  export let votes;

  $: options = votes.map(vote => vote.option);

  function onVote(event) {
    let index = event.detail;
    votes[index].count++;
    status = 'closed';
  }
</script>
<style>
div {
  color: #666666;
  font: 400 1rem "Inter", sans-serif;
}

.overlay {
  background: rgba(242, 243, 245, 0.8);
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;

  display: flex;
  justify-content: center;
  align-items: center;
}

.card-container {
  background: var(--white);
  width: 100%;
  max-width: 400px;
  padding: 2rem 3rem;
  border-radius: 5px;
  box-shadow: 0 0 60px rgba(0, 0, 0, 0.05);
  text-align: center;
  position: relative;
}

.title {
  color: #2e384d
}
</style>
