// lets-vote-vue/src/components/VotingForm.vue
<template>
  <div class="card-container">
    <h2 className="title">Inicie uma votação</h2>
      <form @submit.prevent="handleSubmit">
        <div className="form-field">
          <label>Título:</label>
          <input
            type="text"
            placeholder="O que gostaria de perguntar?"
            v-model="v$.title.$model"
            :class="{ 'field-invalid': v$.title.$error}"
          />
          <div v-for="(error, index) of v$.title.$errors" :key="index">
            <span>{{ error.$message }}</span>
          </div>
        </div>
        
        <div className="form-field">
          <label>Opções de voto:</label>
          <select 
            v-model="v$.threeOptions.$model"
            :class="{ 'field-invalid': v$.threeOptions.$error}"
          >
            <option value=""></option>
            <option value="0">Sim, não</option>
            <option value="1">Sim, não, talvez</option>
          </select>
          <div v-for="(error, index) of v$.threeOptions.$errors" :key="index">
            <span>{{ error.$message }}</span>
          </div>
        </div>

        <button type="submit">Começar</button>
      </form>
  </div>
</template>

<script>
import { reactive } from 'vue'
import useVuelidate from '@vuelidate/core'
import { required, maxLength } from '@vuelidate/validators'
import { setOptions, title } from '../store.js';

export default {
  setup () {
    const state = reactive({
      title: '',
      threeOptions: '',
    });

    const rules = {
      title: {
          required,
          max: maxLength(30)
      },
      threeOptions: {
          required
      },
    }

    const v$ = useVuelidate(rules, state);
   
    return { v$, state }
  },

  methods: {
    handleSubmit() {
      this.v$.$touch()
      if (this.v$.$error) return;
      title.value = this.state.title;
      setOptions(this.state.threeOptions);
      this.$emit('start');
    }
  }

  // data() {
  //   return {
  //     form: {
  //       title: '',
  //       threeOptions: '',
  //     },
  //   }
  // },

  // validations() {
  //   return {
  //     form: {
  //       title: {
  //          required,
  //          max: maxLength(30)
  //       },
  //       threeOptions: {
  //           required
  //       },
  //     },
  //   }
  // },
}
</script>

<style>
.form-field {
  text-align: left;
  margin-bottom: 1rem;
}

.form-field input, select {
  display: block;
  width: 100%;
  height: 2rem;
  margin-top: 0.5rem;
  margin-bottom: 0.5rem;
  color: #2e384d;
  border: solid 1px #666666;
  border-radius: 5px;
}

.form-field input:focus-visible:not(.field-invalid), select:focus-visible {
  outline: #2e384d auto 1px;
}

.form-field span {
  font-size: 0.9rem;
  color: #D65151;
}

.field-invalid {
  border: solid 1px #D65151 !important;
}

.field-invalid:focus-visible {
  outline: #D65151 auto 1px;
}

.form-field select {
  height: 2.25rem;
}
</style>

// lets-vote-svelte/src/components/VotingForm.svelte

<div class="card-container">
  <h2 class="title">Inicie uma votação</h2>
  <form on:submit={handleSubmit}>
    <div class="form-field">
      <label for="title">Título:</label>
      <input
        type="text"
        placeholder="O que gostaria de perguntar?"
        id="title"
        name="title"
        class={`${$errors.required || $errors.maxLength ? 'field-invalid' : ''}`}
        on:blur={handleChange}
        bind:value={$form.title}
      />
      {#if $errors.required}
        <span>{$errors.required}</span>
      {/if}
      {#if $errors.maxLength}
        <span>{$errors.maxLength}</span>
      {/if}
    </div>

    <div class="form-field">
      <label for="threeOptions">Opções de voto:</label>
      <select 
        id="threeOptions"
        name="threeOptions"
        class={`${$errors.optionRequired ? 'field-invalid' : ''}`}
        on:blur={handleChange}
        bind:value={$form.threeOptions}
      >
        <option></option>
        <option value="0">Sim, não</option>
        <option value="1">Sim, não, talvez</option>
      </select>
      {#if $errors.optionRequired}
        <span>{$errors.optionRequired}</span>
      {/if}
    </div>

    <button type="submit">Começar</button>
  </form>
</div>


<script>
  import { createForm } from "svelte-forms-lib";
  import { createEventDispatcher } from 'svelte';

  const dispatcher = createEventDispatcher();

  const { form, errors, state, handleChange, handleSubmit } = createForm({
    initialValues: {
      title: "",
      threeOptions: "",
    },
    validate: values => {
      let errs = {};
      if (values.title === "") {
        errs["required"] = "Título é obrigatório";
      }
      if (values.title?.length > 30) {
        errs["maxLength"] = "Máximo de 30 caracteres";
      }
      if (values.threeOptions === "") {
        errs["optionRequired"] = "Campo obrigatório";
      }
      return errs;
    },
    onSubmit: data => {
      dispatcher('start', data)
    }
  });
</script>

<style>
.card-container {
  background: white;
  width: 100%;
  max-width: 400px;
  padding: 2rem 3rem;
  border-radius: 5px;
  box-shadow: 0 0 60px rgba(0, 0, 0, 0.05);
  text-align: center;
  position: relative;
}

.title {
  color: #2e384d
}

.form-field {
  text-align: left;
  margin-bottom: 1rem;
}

.form-field input, select {
  display: block;
  width: 100%;
  height: 2rem;
  margin-top: 0.5rem;
  margin-bottom: 0.5rem;
  color: #2e384d;
  border: solid 1px #666666;
  border-radius: 5px;
}

.form-field input:focus-visible:not(.field-invalid), select:focus-visible {
  outline: #2e384d auto 1px;
}

.form-field span {
  font-size: 0.9rem;
  color: #D65151;
}

.field-invalid {
  border: solid 1px #D65151 !important;
}

.field-invalid:focus-visible {
  outline: #D65151 auto 1px;
}

.form-field select {
  height: 2.25rem;
}

button, input, select {
  font: 400 1rem "Inter", sans-serif; 
}

button {
  width: 7.5rem;
  height: 2.5rem;

  margin-top: 2rem;
  margin-bottom: 2rem;

  border: 0;
  border-radius: 5px;

  background: #5965e0;
  color: #fff;
  font-size: 1.25rem;
  font-weight: 600;

  cursor: pointer;

  transition: background-color 0.2s;
}

button:hover {
  background: #4953b8;
}
</style>
