// lets-vote-vue/src/components/Result.vue
<template>
  <div class="result-container">
    <p v-for="vote in votes" :key="vote.option">
      {{ vote.option }} - {{ vote.count }} votos ({{ calculatePercentage(vote.count) }}%)
    </p>
  </div>
</template>

<script>
export default {
  name: 'Result',
  props: {
    votes: Array,
  },
  methods: {
    calculatePercentage(value) {
      return Math.round(100 * value/this.totalVotes);
    }
  },
  computed: {
    totalVotes() {
      let total = 0;
      for (let vote of this.votes) {
        total += vote.count;
      }

      return total;
    }
  }
}
</script>

<style>

</style>

// lets-vote-react/src/components/Result.js
import { useEffect, useState } from "react";

export default function Result(props) {
  const [totalVotes, setTotalVotes] = useState(1);

  const result = props.votes.map((vote, index) => (
    <p key={index.toString()}>
      {index + 1}. {vote.option} - {vote.count} votos ({calculatePercentage(vote.count)}%)
    </p>
  ));

  function calculatePercentage(value) {
    return Math.round(100 * value / totalVotes);
  }

  useEffect(() => {
    let aux = 0;
    for (let vote of props.votes) {
      aux += vote.count;
    }
    setTotalVotes(aux);
  }, [props.votes]);

  return (
    <div>
      {result}
    </div>
  );
}
