// lets-vote-angular/src/components/votingCard/votingCard.component.ts
import { Component, Input } from "@angular/core";
import { StoreService } from "src/store.service";

@Component({
  selector: 'voting-card',
  templateUrl: './votingCard.component.html',
  styleUrls: ['./votingCard.component.css']
})

export class VotingCardComponent {
  constructor(public store: StoreService) { }

  @Input() status: string = '';
  votes: { option: string, count: number }[] = [];

  ngOnInit() {
    this.votes = this.store.options.map(option => {
      return {
        option: option,
        count: 0,
      };
    });
  }

  onVote(index: number) {
    this.votes[index].count++;
    this.status = 'closed';
  }
}


<div class="card-container">
  <h2 class="title">{{store.title}}</h2>
    <div *ngIf="status === 'open'; else result">
      <booth [options]="store.options" (vote)="onVote($event)"></booth>
    </div>
    <ng-template #result>
      <result [votes]="votes"></result>
    </ng-template> 
</div>

// lets-vote-react/src/components/VotingCard.js
import { useEffect, useState } from 'react';

import '../styles/voting-card.css';

import Booth from './Booth';
import Result from './Result';

export default function VotingCard(props) {
  const [options, setOptions] = useState([]);
  const [status, setStatus] = useState(props.status);

  useEffect(() => {
    setOptions(props.votes.map(vote => vote.option));
  }, [props.votes]);

  function vote(index) {
    props.votes[index].count++;
    setStatus("closed");
  }

  return (
    <div className="overlay">
      <div className="card-container">
        <h2 className="title">{props.title}?</h2>
        {status === 'open'
          ? <Booth options={options} onVote={vote} />
          : <Result votes={props.votes} />
        }
      </div>
    </div>
  );
}
