// lets-vote-angular/src/components/votingForm/votingForm.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: 'voting-form',
  templateUrl: './votingForm.component.html',
  styleUrls: ['./votingForm.component.css']
})

export class VotingFormComponent {
  title = '';
  threeOptions = '';
}

<div class="card-container">
  <h2 class="title">Inicie uma votação</h2>
    <form>
      <div class="form-field">
        <label>Título:</label>
        <input
          #input="ngModel"
          name="title"
          type="text"
          placeholder="O que gostaria de perguntar?"
          [(ngModel)]="title"
          required
          maxlength="30"
        />
        <div *ngIf="input.invalid && input.touched">
          <span *ngIf="input.errors!.required">
            Título é obrigatório.
          </span>
          <span *ngIf="input.errors!.maxlength">
            Máximo de 30 caracteres
          </span>
        </div>
      </div>
      
      <div class="form-field">
        <label>Opções de voto:</label>
        <select 
          #select="ngModel"
          [(ngModel)]="threeOptions"
          required
        >
          <option value="0">Sim, não</option>
          <option value="1">Sim, não, talvez</option>
        </select>
        <div *ngIf="select.invalid && select.touched">
          <span *ngIf="select.errors!.required">
            Opções são obrigatórias.
          </span>
        </div>
      </div>

      <button type="submit">Começar</button>
    </form>
</div>

// lets-vote-react/src/components/VotingForm.js
import '../styles/voting-form.css';

import { useForm } from "react-hook-form";

export default function VotingForm(props) {
  const { register, handleSubmit, formState: { errors } } = useForm();
  const onSubmit = data => props.onStart(data);

  return (
    <div className="card-container">
      <h2 className="title">Inicie uma votação</h2>
      <form onSubmit={handleSubmit(onSubmit)}>
        <div className="form-field">
          <label>Título:</label>
          <input
            type="text"
            placeholder="O que gostaria de perguntar?"
            {...register("title", { required: true, maxLength: 30 })}
            className={`${errors.title ? 'field-invalid' : ''}`}
          />
          {errors.title?.type === 'required' && <span>Título é obrigatório</span>}
          {errors.title?.type === 'maxLength' && <span>Máximo de 30 caracteres</span>}
        </div>

        <div className="form-field">
          <label>Opções de voto:</label>
          <select {...register("threeOptions", { required: true })}>
            <option value="0">Sim, não</option>
            <option value="1">Sim, não, talvez</option>
          </select>
        </div>

        <button type="submit">Começar</button>
      </form>

    </div>
  )
}
